### ISSUE TITLE
Input filter mechanism

### ISSUE THREAD

**Issue by gaborantal** [Persper/javascript-call-graph#18]
We need a filtering mechanism which can help us in directory-based analysis. Let's take an example: if we are analyzing a project, like `node src/main.js /home/user/path/to/project` is possibly contains a normal project (with src or lib directory *and tests* directory). We do not want to analyze the calls between tests and source normally. Also there are cases when we need to filter out some calls (like a `jquery.js` in the lib directory). 

So we need a great filtering mechanism which can filter out the unwanted files. As I mentioned [here](https://github.com/Persper/javascript-call-graph/issues/13#issuecomment-415319930), the work of the filtering mechanism can introduce some inconsistencies. To overcome this, our first idea on filtering is the following:

1. Introduce a new command line option `--filter` which takes the filter file as a parameter which is a text file.
2. The filter file will contain all the inclusion/exclusion filters, ordered. All the lines in the filter file is a comment line or a filtering line. Filtering lines start with plus or minus sign (whether the line is an inclusion or exclusion filter). If the filter line is not correct, we skip it and warn the user about that fact.
3. The filtering should happen after all the input files are collected and the duplications are removed.

The proposed filter file looks like the following:
```
# Filter out all source files starting with "test":
-test[^\.]*.js
# But test576.js is needed:
+test576.js
# Furthermore, files beginning with "test1742" are also needed:
+test1742[^\.]*.js
# Finally, test1742_b.js is not needed:
-test1742_b.js
```

What do you think about the filtering?

**Comment by zizo007** [comment]
LGTM

**Comment by UltimateBeaver** [comment]
LGTM. I'll go ahead and assign this to Gabor. Thanks!

**Comment by gaborantal** [comment]
Would you please assign this task to @xavvior?

**Comment by UltimateBeaver** [comment]
Sure thing.

**Comment by UltimateBeaver** [comment]
Hmm, I don't see @xavvior in the drop-down menu of assignees. Is there a setting change to be made to allow this?

**Comment by xavvior** [comment]
I'm here, so maybe you can assign me

**Comment by UltimateBeaver** [comment]
Nope, still not finding you in the menu. Maybe I can only assign to the creator of issue or contributors of the repo? Then I should merge your PR first and try again.

**Comment by xavvior** [comment]
Maybe you are right. I have an pending PR, we wait for merge (and modifications) and after try again. Until stay the assigne on Gábor this issue :)

**Comment by xavvior** [comment]
Guys, I checked the conditions and expressions and I have perception (and idea).
So I see, that the wildcard expression is the [^\.]* expression. My idea is the like SQL syntax, that the wildcard lets be as simple *.

So:
```
# Filter out all source files starting with "test":
-test*.js
# But test576.js is needed:
+test576.js
# Furthermore, files beginning with "test1742" are also needed:
+test1742*.js
# Finally, test1742_b.js is not needed:
-test1742_b.js
```

The file name can't contain * character and maybe easier understand the filter rules. Or you think, that in the future we will introduce regexp in filter expression?

**Comment by xavvior** [comment]
Thanks for merge, this issue has been closeable. :)
