### ISSUE TITLE
Unified JSON output format

### ISSUE THREAD

**Issue by xavvior** [Persper/javascript-call-graph#9]
Hi,
a unified JSON output format for this module should be implemented.
I have concrete suggestion for this, which we use currently in our implementations.
I would like to ask you to check whether it is good for you and give feedback about it.

A command line argument should be made first, which we can choose: old-style output as lines (like now) or the new unified JSON format. It would make additional processing easier - eg: reuse in another modules, processing the calls etc.

Secondly, the my suggestion for unified format:
```
[  
   {  
      source:{  
         label:null,
         file:null,
         start:{  row:null, column:null },
         end:{  row:null, column:null },
         range:{  start:null, end:null }
      },
      target:{  
         label:null,
         file:null,
         start:{  row:null, column:null },
         end:{  row:null, column:null },
         range:{  start:null, end:null }
      }
   }
]
```

The elements of the list represent one binding (call) between 2 nodes with source and target informations.

Waiting for your feedbacks,
Best regards,
Alex Szarka

**Comment by xavvior** [comment]
Hi, sorry for format. The Github shows as incorrectly the JSON code, so I push'd into pastebin the format.
https://pastebin.com/XvP92vDH

Alex

**Comment by UltimateBeaver** [comment]
Thanks for creating this PR for discussion. The format looks good to me with only one question, why is `range` field necessary given that there are already `start` and `end` fields?

**Comment by xavvior** [comment]
In AST have a range field, which help us identify the node in our module. Maybe easier (for me), than with the start and end informations. If neccessary, I can remove from sample the range, but I think, that it is not a redundant information and maybe can be useful. What is your opinion about this?

**Comment by UltimateBeaver** [comment]
Maybe an example here can help me understand the difference between `source.start` and `source.range.start`. Do they store different info?

**Comment by xavvior** [comment]
The source.start contains the start row and start column. This is relative information. The number of rows from first line and the number of columns counted from start of row.
In contrast of this, the source.range.start represent the distance from first line first column.

Example code:
`
//ex
function x(){
 y();
}
function y(){}
`
From the X call Y method. In current example the rows and columns from source.start is:
source :: start -> rows: 3, columns: 2; end -> rows: 3, columns: 6
source :: range:: start:: 18, end:: 21

I think, that it more useful, cuz more few information require for same task.

**Comment by UltimateBeaver** [comment]
Ah, I see, it's index-based range. Yeah, it makes sense to include this info. Btw, if function `X` calls function `Y`, which one is considered the source? I thought it should be `X`, but your example suggested `Y` being the source.

**Comment by xavvior** [comment]
This just an example, I writed for only illustrating. :) Of course the source give by current implementation :) I not check'd, that how work currently, but the base is the main.js:
```if (args.cg) {
    cg.edges.iter(function (call, fn) {
        console.log(pp(call) + " -> " + pp(fn));
    });
}```
who from the pp(call) build the source and from pp(fn) build the target :) 


I have already an implementation for this, so I can illustrate in another fork. 
You can assignee to me this feature please?

**Comment by UltimateBeaver** [comment]
Gotcha, done:)

**Comment by xavvior** [comment]
#17
